package com.shopwithanish.ecommerse.application.Model;


import com.shopwithanish.ecommerse.application.Enums.AppPaymentStatus;
import com.shopwithanish.ecommerse.application.Enums.PaymentGatewaySTATUS;
import com.shopwithanish.ecommerse.application.Enums.PaymentMethod;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Entity
public class Payment {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(nullable = false)
    private Long paymentId;
    //this paymentid generated by our app

    private Double amount;
    private LocalDateTime initiatedAt;

    @Enumerated(value = EnumType.STRING)
    private PaymentMethod paymentMethod;

    @Enumerated(EnumType.STRING)
    private AppPaymentStatus paymentStatus;

    //pg for paymentgateway razorpay ,stripe
    private String pgPaymentId;
    //this id generated by paymentgateway at their site


    @Enumerated(value = EnumType.STRING)
    private PaymentGatewaySTATUS paymentGatewaySTATUS;

    private String pgResponceMessage;
    private String pgName;

    @OneToOne(mappedBy = "payment" , cascade = CascadeType.ALL)
    private Order order;


    public Payment(Long paymentid, PaymentMethod paymentMethod, String pgName, String pgPaymentId, String pgResponceMessage, PaymentGatewaySTATUS paymentGatewaySTATUS) {
        this.paymentId = paymentid;
        this.paymentMethod = paymentMethod;
        this.pgName = pgName;
        this.pgPaymentId = pgPaymentId;
        this.pgResponceMessage = pgResponceMessage;
        this.paymentGatewaySTATUS = paymentGatewaySTATUS;
    }
}
